apiVersion: v1
kind: Pod
metadata:
  name: proj1
  labels:
    name: proj1
spec:
  containers:
  - name: proj1
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
